### ISSUE TITLE
查询到的cookie有多个，具体使用哪一个？

### ISSUE THREAD

**Issue by lukemin** [xiaomustudent/glados-checkin#1]
![1593484740(1)](https://user-images.githubusercontent.com/12003375/86077106-faf27380-babd-11ea-807d-c927bb4e104d.png)

**Comment by xiaomustudent** [comment]
你看看
![}T9K$96`6RA Y5MN4QDGFZJ](https://user-images.githubusercontent.com/62041219/86077645-e9f63200-babe-11ea-90ab-5e95f6ab324d.png)

**Comment by lukemin** [comment]
谢谢，我网站登录的是https://glados.live/没有问题吧？

**Comment by xiaomustudent** [comment]
没问题啊 就是这个网址啊 如果是教育邮箱 可以在下面for education 申请edu plan

**Comment by lukemin** [comment]
已经成功申请edu plan，谢谢提供此脚本

**Comment by xiaomustudent** [comment]
没什么没什么 玩的开心
