### ISSUE TITLE
可以用telethon调用telegram api回复

### ISSUE THREAD

**Issue by 0honus0** [xiaomustudent/glados-checkin#16]
rt
有时间你可以写下

**Comment by xiaomustudent** [comment]
是tg机器人签到的 获取不了签到api

**Comment by 0honus0** [comment]
> 是tg机器人签到的 获取不了签到api

就模拟自己每天给那个机器人发个消息就行了发送

**Comment by xiaomustudent** [comment]
......咋模拟 tg发信息有api可以调用**？**

**Comment by 0honus0** [comment]
> ......咋模拟 tg发信息有api可以调用**？**
是的，你看下telethon这个库，Python封装的官方api
群里刚发公告签到上限30天了。感觉没必要搞了

**Comment by xiaomustudent** [comment]
没意义玩了 当时写这个也就是玩玩

**Comment by 0honus0** [comment]
> 没意义玩了 当时写这个也就是玩玩

写倒是简单，不超过10行
问题是官方加签到上限了，无解
安心用付费的吧
