### ISSUE TITLE
大佬,看下,报错了,这是拿到问题

### ISSUE THREAD

**Issue by wx-io** [xiaomustudent/glados-checkin#2]
Checkin1s
##[error]Process completed with exit code 1.
Run pyth***3 checkin.py 
Traceback (most recent call last):
  File "checkin.py", line 38, in <module>
    start()
  File "checkin.py", line 26, in start
    time = state.js***()['data']['leftDays']
KeyError: 'data'
##[error]Process completed with exit code 1.

**Comment by xiaomustudent** [comment]
你时并不是改代码了 
time = state.json()['data']['leftDays']  你on呢

**Comment by wx-io** [comment]
if 'message' in checkin.text:
        mess = checkin.json()['message']
        time = state.json()['data']['leftDays']
        time = time.split('.')[0]
        #print(time)
        if sever == 'on':

我看了半天,代码没有改,原版的,奇怪了

**Comment by xiaomustudent** [comment]
改回来就是 没事

**Comment by wx-io** [comment]
大佬,麻烦了,我重新克隆的代码

还是有报错

 Checkin1s
##[error]Process completed with exit code 1.
Run python3 checkin.py 
Traceback (most recent call last):
  File "checkin.py", line 37, in <module>
    start()
  File "checkin.py", line 25, in start
    time = state.json()['data']['leftDays']
KeyError: 'data'
##[error]Process completed with exit code 1.

**Comment by xiaomustudent** [comment]
你cookie 啥的 弄对了么  不应该这样的 啃你cookie失效 你重新弄一下

**Comment by wx-io** [comment]
估计是cookie的问题
