### ISSUE TITLE
云函数执行时报错了

### ISSUE THREAD

**Issue by wajika** [xiaomustudent/glados-checkin#21]
{

  "errorCode": -1,

  "errorMessage": "user code exception caught",

  "stackTrace": "Traceback (most recent call last):\n  File \"/var/user/index.py\", line 36, in main_handler\n    return start()\n  File \"/var/user/index.py\", line 21, in start\n    checkin = requests.post(url,headers={'cookie': cookie ,'referer': referer,'origin':origin,'user-agent':useragent,'content-type':'application/json;charset=UTF-8'},data=json.dumps(payload))\nNameError: name 'json' is not defined",

  "statusCode": 430

}

**Comment by xiaomustudent** [comment]
用github多好 云函数不稳定
