### ISSUE TITLE
已经好些天无法+1了

### ISSUE THREAD

**Issue by hyy34** [xiaomustudent/glados-checkin#27]
一直都是显示xxx Your lucky chance is 33%，已经连续能有10多天了。难道用脚本不行了？33%的几率也不至于1次也不成功啊。。

**Comment by UTSOURCE** [comment]
我也是

**Comment by xiaomustudent** [comment]
去 glados tg群 让管理员把概率提提

**Comment by UTSOURCE** [comment]
@xiaomustudent tg群多少

**Comment by xiaomustudent** [comment]
https://t.me/glados_network

**Comment by UTSOURCE** [comment]
![image](https://user-images.githubusercontent.com/14830459/113825527-ad750680-97b3-11eb-82cf-ee4f88b15601.png)
@xiaomustudent

**Comment by UTSOURCE** [comment]
哈哈

**Comment by xiaomustudent** [comment]
群没了.....免费服务不提供技术支持...没事 在注册个号

**Comment by hyy34** [comment]
> 群没了.....免费服务不提供技术支持...没事 在注册个号
再注册不也是无法签到+1了。。。

**Comment by hyy34** [comment]
> 群没了.....免费服务不提供技术支持...没事 在注册个号

再注册不也无法+1了。

**Comment by xiaomustudent** [comment]
人家吧概率调到33%了 没办法 人家不愿意

**Comment by hyy34** [comment]
> 人家吧概率调到33%了 没办法 人家不愿意

33%，开玩笑，估计是3.3%吧。。。我已经一个多月了无法+1了。天天提示我的33%

**Comment by adinxu** [comment]
> > 人家吧概率调到33%了 没办法 人家不愿意
> 
> 33%，开玩笑，估计是3.3%吧。。。我已经一个多月了无法+1了。天天提示我的33%

估计是薅羊毛太多了，记得我当时签到了十几天都有，天数都没变过的
