### ISSUE TITLE
怎么使用？

### ISSUE THREAD

**Issue by cat0000000** [xiaomustudent/glados-checkin#6]
这个cookie放在哪里，还有on怎么开，填在哪里，腾讯云函数可不可以详细一点

**Comment by xiaomustudent** [comment]
用 云函数


import requests, time, re, json, base64, argparse
from urllib import parse
# server酱开关，填0不开启(默认)，填1只开启cookie失效通知，填2同时开启cookie失效通知和签到成功通知
sever = '2'
# 填写server酱sckey,不开启server酱则不用填
sckey = 'server酱sckey'
# 填入glados账号对应cookie
cookie = '这里改cookie'
referer = 'https://glados.rocks/console/checkin'

def start():
    url= "https://glados.rocks/api/user/checkin"
    url2= "https://glados.rocks/api/user/status"
    checkin = requests.post(url,headers={'cookie': cookie ,'referer': referer })
    state =  requests.get(url2,headers={'cookie': cookie ,'referer': referer})
   # print(res)

    if 'message' in checkin.text:
        mess = checkin.json()['message']
        time = state.json()['data']['leftDays']
        time = time.split('.')[0]
        #print(time)
        if sever == '2':
            requests.get('https://sc.ftqq.com/' + sckey + '.send?text='+mess+'，you have '+time+' days left')
    else:
        requests.get('https://sc.ftqq.com/' + sckey + '.send?text=cookie过期')

def main_handler(event, context):
  return start()

if __name__ == '__main__':
  start()

**Comment by xiaomustudent** [comment]
新建空白 py3.6 所有的复制到云函数那  自己在设置一个触发器 0 0 7 * * * *
