### ISSUE TITLE
配置正确，但测试返回null

### ISSUE THREAD

**Issue by Wilnk** [xiaomustudent/glados-checkin#7]
我把项目里的checkin.py文件代码完全复制，并且在函数配置的环境变量里配置了 SERVE 、SCKEY和COOKIE，和直接写进代码里面进行测试，发觉返回值是空！serve酱也没有通知 这是什么原因？

![image](https://user-images.githubusercontent.com/46810638/87323950-05067e80-c562-11ea-8be9-8c707ddb60df.png)

**Comment by xiaomustudent** [comment]
可能你cookie啥的没弄好 或是sckey  检查一下

**Comment by Wilnk** [comment]
这是我的云函数代码

import requests,json,os

# server酱开关，填off不开启(默认)，填on同时开启cookie失效通知和签到成功通知
sever = os.environ["SERVE"]
# 填写server酱sckey,不开启server酱则不用填
sckey = os.environ["SCKEY"]
# 填入glados账号对应cookie
cookie = os.environ["COOKIE"]




def start():
    
    url= "https://glados.rocks/api/user/checkin"
    url2= "https://glados.rocks/api/user/status"
    referer = 'https://glados.rocks/console/checkin'
    checkin = requests.post(url,headers={'cookie': cookie ,'referer': referer })
    state =  requests.get(url2,headers={'cookie': cookie ,'referer': referer})
   # print(res)

    if 'message' in checkin.text:
        mess = checkin.json()['message']
        time = state.json()['data']['leftDays']
        time = time.split('.')[0]
        #print(time)
        if sever == 'on':
            requests.get('https://sc.ftqq.com/' + sckey + '.send?text='+mess+'，you have '+time+' days left')
    else:
        requests.get('https://sc.ftqq.com/' + sckey + '.send?text=cookie过期')

def main_handler(event, context):
  return start()

if __name__ == '__main__':
    start()


配置是正确的，因为我在github上的运行是通过的 ，但是云函数还是返回null

![image](https://user-images.githubusercontent.com/46810638/87850456-f5e94d00-c922-11ea-9efe-ab0edceeb245.png)

**Comment by xiaomustudent** [comment]
github的运行好点  github上运行有微信通知么

**Comment by Wilnk** [comment]
github上可以完美运行，但就是不知道云函数的哪一步错了

**Comment by xiaomustudent** [comment]
import requests, time, re, json, base64, argparse
sever = '2'
sckey = '********************************'
cookie = '***************************************************’; 
referer = 'https://glados.rocks/console/checkin'

def start():
    url= "https://glados.rocks/api/user/checkin"
    url2= "https://glados.rocks/api/user/status"
    checkin = requests.post(url,headers={'cookie': cookie ,'referer': referer })
    state =  requests.get(url2,headers={'cookie': cookie ,'referer': referer})
   # print(res)

    if 'message' in checkin.text:
        mess = checkin.json()['message']
        time = state.json()['data']['leftDays']
        time = time.split('.')[0]
        #print(time)
        if sever == '2':
            requests.get('https://sc.ftqq.com/' + sckey + '.send?text='+mess+'，you have '+time+' days left')
    else:
        requests.get('https://sc.ftqq.com/' + sckey + '.send?text=cookie过期')

def main_handler(event, context):
  return start()

if __name__ == '__main__':
  start()









#用上面的，把cookie 和sckey 改了 就行

**Comment by Wilnk** [comment]
![image](https://user-images.githubusercontent.com/46810638/87850720-e1a64f80-c924-11ea-955e-49ed8db5e77a.png)

只改两个，但是请求失败

**Comment by xiaomustudent** [comment]
[新建文本文档 (2).txt](https://github.com/xiaomustudent/glados-checkin/files/4941479/2.txt)

**Comment by Wilnk** [comment]
成功了、谢谢大佬
